version: '3.8'

services:
  backend:
    build: ./backend
    container_name: nest-backend
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: yourpassword
      DB_NAME: nestdb

  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "5173:80"

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: nestdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
