version: '3.8'

services:
  backend:
    build: ./backend
    container_name: nest-backend
    ports:
      - "3000:5000"
    depends_on:
      - mysql
    env_file:
      - ./backend/.env
    

  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "5173:80"

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: TodoApp
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
